import math

a = int(input("Введите первое число: "))
b = int(input("Введите второе число: "))
print(a + b)
print(a - b)
print(b - a)
print(a * b)
print(a / b)
print(b / a)
print(a ** b)
print(b ** a)
print(math.sin(a))
print(math.sin(b))
print(math.cos(a))
print(math.cos(b))
print(str(a) + str(b))
